"""initial_postgresql_schema

Revision ID: 30d14e9fbd43
Revises: 
Create Date: 2025-11-08 04:36:28.998195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30d14e9fbd43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanicilar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kullanici_adi', sa.String(length=50), nullable=False),
    sa.Column('sifre_hash', sa.String(length=255), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.Enum('sistem_yoneticisi', 'admin', 'depo_sorumlusu', 'kat_sorumlusu', name='kullanici_rol'), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('son_giris', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kullanici_adi')
    )
    op.create_table('oteller',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('vergi_no', sa.String(length=50), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otomatik_raporlar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rapor_tipi', sa.Enum('gunluk_stok', 'stok_kontrolu', 'zimmet_ozeti', 'minibar_tuketim', name='rapor_tipi'), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('rapor_verisi', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('toplam_urun', sa.Integer(), nullable=True),
    sa.Column('kritik_stok_sayisi', sa.Integer(), nullable=True),
    sa.Column('toplam_deger', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('olusturan', sa.String(length=100), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rapor_tipi_tarih', 'otomatik_raporlar', ['rapor_tipi', 'olusturma_tarihi'], unique=False)
    op.create_table('sistem_ayarlari',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anahtar', sa.String(length=100), nullable=False),
    sa.Column('deger', sa.Text(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anahtar')
    )
    op.create_table('urun_gruplari',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grup_adi', sa.String(length=100), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grup_adi')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('kullanici_adi', sa.String(length=100), nullable=False),
    sa.Column('kullanici_rol', sa.String(length=50), nullable=False),
    sa.Column('islem_tipi', sa.Enum('create', 'update', 'delete', 'login', 'logout', 'view', 'export', 'import', name='audit_islem_tipi'), nullable=False),
    sa.Column('tablo_adi', sa.String(length=100), nullable=False),
    sa.Column('kayit_id', sa.Integer(), nullable=True),
    sa.Column('eski_deger', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('yeni_deger', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('degisiklik_ozeti', sa.Text(), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('ip_adresi', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('islem_tarihi', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('basarili', sa.Boolean(), nullable=True),
    sa.Column('hata_mesaji', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kullanici_tarih', 'audit_logs', ['kullanici_id', 'islem_tarihi'], unique=False)
    op.create_index('idx_tablo_kayit', 'audit_logs', ['tablo_adi', 'kayit_id'], unique=False)
    op.create_index('idx_tarih', 'audit_logs', ['islem_tarihi'], unique=False)
    op.create_table('hata_loglari',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('hata_tipi', sa.String(length=100), nullable=False),
    sa.Column('hata_mesaji', sa.Text(), nullable=False),
    sa.Column('hata_detay', sa.Text(), nullable=True),
    sa.Column('modul', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('ip_adresi', sa.String(length=50), nullable=True),
    sa.Column('tarayici', sa.String(length=200), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cozuldu', sa.Boolean(), nullable=True),
    sa.Column('cozum_notu', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('katlar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('otel_id', sa.Integer(), nullable=False),
    sa.Column('kat_adi', sa.String(length=50), nullable=False),
    sa.Column('kat_no', sa.Integer(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['otel_id'], ['oteller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personel_zimmet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('zimmet_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('iade_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teslim_eden_id', sa.Integer(), nullable=True),
    sa.Column('durum', sa.Enum('aktif', 'tamamlandi', 'iptal', name='zimmet_durum'), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['personel_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['teslim_eden_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sistem_loglari',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('islem_tipi', sa.String(length=50), nullable=False),
    sa.Column('modul', sa.String(length=100), nullable=False),
    sa.Column('islem_detay', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_adresi', sa.String(length=50), nullable=True),
    sa.Column('tarayici', sa.String(length=200), nullable=True),
    sa.Column('islem_tarihi', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urunler',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grup_id', sa.Integer(), nullable=False),
    sa.Column('urun_adi', sa.String(length=200), nullable=False),
    sa.Column('barkod', sa.String(length=50), nullable=True),
    sa.Column('birim', sa.String(length=20), nullable=True),
    sa.Column('kritik_stok_seviyesi', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grup_id'], ['urun_gruplari.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barkod')
    )
    op.create_table('odalar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kat_id', sa.Integer(), nullable=False),
    sa.Column('oda_no', sa.String(length=20), nullable=False),
    sa.Column('oda_tipi', sa.String(length=50), nullable=True),
    sa.Column('kapasite', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qr_kod_token', sa.String(length=64), nullable=True),
    sa.Column('qr_kod_gorsel', sa.Text(), nullable=True),
    sa.Column('qr_kod_olusturma_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('misafir_mesaji', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['kat_id'], ['katlar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oda_no'),
    sa.UniqueConstraint('qr_kod_token')
    )
    op.create_index('idx_qr_token', 'odalar', ['qr_kod_token'], unique=False)
    op.create_table('personel_zimmet_detay',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zimmet_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('miktar', sa.Integer(), nullable=False),
    sa.Column('kullanilan_miktar', sa.Integer(), nullable=True),
    sa.Column('kalan_miktar', sa.Integer(), nullable=True),
    sa.Column('iade_edilen_miktar', sa.Integer(), nullable=True),
    sa.Column('kritik_stok_seviyesi', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.ForeignKeyConstraint(['zimmet_id'], ['personel_zimmet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stok_hareketleri',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('hareket_tipi', sa.Enum('giris', 'cikis', 'devir', 'sayim', name='hareket_tipi'), nullable=False),
    sa.Column('miktar', sa.Integer(), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('islem_yapan_id', sa.Integer(), nullable=True),
    sa.Column('islem_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['islem_yapan_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minibar_dolum_talepleri',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oda_id', sa.Integer(), nullable=False),
    sa.Column('talep_tarihi', sa.DateTime(timezone=True), nullable=False),
    sa.Column('durum', sa.Enum('beklemede', 'tamamlandi', 'iptal', name='dolum_talep_durum'), nullable=False),
    sa.Column('tamamlanma_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['oda_id'], ['odalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oda_durum', 'minibar_dolum_talepleri', ['oda_id', 'durum'], unique=False)
    op.create_index('idx_talep_tarihi', 'minibar_dolum_talepleri', ['talep_tarihi'], unique=False)
    op.create_table('minibar_islemleri',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oda_id', sa.Integer(), nullable=False),
    sa.Column('personel_id', sa.Integer(), nullable=False),
    sa.Column('islem_tipi', sa.Enum('ilk_dolum', 'kontrol', 'doldurma', 'ek_dolum', name='minibar_islem_tipi'), nullable=False),
    sa.Column('islem_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['oda_id'], ['odalar.id'], ),
    sa.ForeignKeyConstraint(['personel_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oda_tarih', 'minibar_islemleri', ['oda_id', 'islem_tarihi'], unique=False)
    op.create_index('idx_personel_tarih', 'minibar_islemleri', ['personel_id', 'islem_tarihi'], unique=False)
    op.create_table('qr_kod_okutma_loglari',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oda_id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=True),
    sa.Column('okutma_tarihi', sa.DateTime(timezone=True), nullable=False),
    sa.Column('okutma_tipi', sa.Enum('kat_sorumlusu', 'misafir', name='qr_okutma_tipi'), nullable=False),
    sa.Column('ip_adresi', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('basarili', sa.Boolean(), nullable=False),
    sa.Column('hata_mesaji', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['oda_id'], ['odalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qr_kullanici_tarih', 'qr_kod_okutma_loglari', ['kullanici_id', 'okutma_tarihi'], unique=False)
    op.create_index('idx_qr_oda_tarih', 'qr_kod_okutma_loglari', ['oda_id', 'okutma_tarihi'], unique=False)
    op.create_index('idx_okutma_tipi', 'qr_kod_okutma_loglari', ['okutma_tipi'], unique=False)
    op.create_table('minibar_islem_detay',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('islem_id', sa.Integer(), nullable=False),
    sa.Column('urun_id', sa.Integer(), nullable=False),
    sa.Column('baslangic_stok', sa.Integer(), nullable=True),
    sa.Column('bitis_stok', sa.Integer(), nullable=True),
    sa.Column('tuketim', sa.Integer(), nullable=True),
    sa.Column('eklenen_miktar', sa.Integer(), nullable=True),
    sa.Column('zimmet_detay_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['islem_id'], ['minibar_islemleri.id'], ),
    sa.ForeignKeyConstraint(['urun_id'], ['urunler.id'], ),
    sa.ForeignKeyConstraint(['zimmet_detay_id'], ['personel_zimmet_detay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('minibar_islem_detay')
    op.drop_index('idx_okutma_tipi', table_name='qr_kod_okutma_loglari')
    op.drop_index('idx_qr_oda_tarih', table_name='qr_kod_okutma_loglari')
    op.drop_index('idx_qr_kullanici_tarih', table_name='qr_kod_okutma_loglari')
    op.drop_table('qr_kod_okutma_loglari')
    op.drop_index('idx_personel_tarih', table_name='minibar_islemleri')
    op.drop_index('idx_oda_tarih', table_name='minibar_islemleri')
    op.drop_table('minibar_islemleri')
    op.drop_index('idx_talep_tarihi', table_name='minibar_dolum_talepleri')
    op.drop_index('idx_oda_durum', table_name='minibar_dolum_talepleri')
    op.drop_table('minibar_dolum_talepleri')
    op.drop_table('stok_hareketleri')
    op.drop_table('personel_zimmet_detay')
    op.drop_index('idx_qr_token', table_name='odalar')
    op.drop_table('odalar')
    op.drop_table('urunler')
    op.drop_table('sistem_loglari')
    op.drop_table('personel_zimmet')
    op.drop_table('katlar')
    op.drop_table('hata_loglari')
    op.drop_index('idx_tarih', table_name='audit_logs')
    op.drop_index('idx_tablo_kayit', table_name='audit_logs')
    op.drop_index('idx_kullanici_tarih', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('urun_gruplari')
    op.drop_table('sistem_ayarlari')
    op.drop_index('idx_rapor_tipi_tarih', table_name='otomatik_raporlar')
    op.drop_table('otomatik_raporlar')
    op.drop_table('oteller')
    op.drop_table('kullanicilar')
    # ### end Alembic commands ###
