"""Add developer dashboard monitoring models

Revision ID: 646cb7ed296e
Revises: 0d9625cc0181
Create Date: 2025-11-12 18:34:29.840494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '646cb7ed296e'
down_revision = '0d9625cc0181'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('job_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_background_jobs_job_id', 'background_jobs', ['job_id'], unique=False)
    op.create_index('idx_background_jobs_started', 'background_jobs', ['started_at'], unique=False)
    op.create_index('idx_background_jobs_status', 'background_jobs', ['status'], unique=False)
    op.create_table('backup_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backup_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'failed', name='backup_status'), nullable=False),
    sa.Column('restore_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backup_id')
    )
    op.create_index('idx_backup_history_backup_id', 'backup_history', ['backup_id'], unique=False)
    op.create_index('idx_backup_history_created', 'backup_history', ['created_at'], unique=False)
    op.create_table('config_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('old_content', sa.Text(), nullable=True),
    sa.Column('new_content', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_audit_changed', 'config_audit', ['changed_at'], unique=False)
    op.create_index('idx_config_audit_filename', 'config_audit', ['filename'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('execution_time', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_query_logs_endpoint', 'query_logs', ['endpoint'], unique=False)
    op.create_index('idx_query_logs_time', 'query_logs', ['execution_time'], unique=False)
    op.create_index('idx_query_logs_timestamp', 'query_logs', ['timestamp'], unique=False)
    op.drop_table('urun_trend_analizi')
    op.drop_table('urun_fiyat_gecmisi')
    op.drop_table('roi_hesaplamalari')
    op.drop_table('bedelsiz_limitler')
    op.drop_table('kampanyalar')
    op.drop_table('sezon_fiyatlandirma')
    op.drop_table('tuketim_kalibi')
    op.drop_table('oda_tipi_satis_fiyatlari')
    op.drop_table('tedarikciler')
    op.drop_table('urun_tedarikci_fiyatlari')
    op.drop_table('bedelsiz_kullanim_log')
    op.drop_table('donemsel_kar_analizi')
    op.drop_table('fiyat_guncelleme_kurallari')
    op.alter_column('audit_logs', 'islem_tipi',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('login', 'logout', 'create', 'update', 'delete', 'view', 'export', 'import', 'backup', 'restore', name='audit_islem_tipi'),
               existing_nullable=False,
               postgresql_using='islem_tipi::audit_islem_tipi')
    op.alter_column('audit_logs', 'eski_deger',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'yeni_deger',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'islem_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('idx_kullanici_tarih'), table_name='audit_logs')
    op.create_index('idx_kullanici_tarih', 'audit_logs', ['kullanici_id', 'islem_tarihi'], unique=False)
    op.drop_index(op.f('idx_tablo_kayit'), table_name='audit_logs')
    op.create_index('idx_tablo_kayit', 'audit_logs', ['tablo_adi', 'kayit_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'kullanicilar', ['kullanici_id'], ['id'])
    op.create_index('idx_dosya_islem_kodu', 'dosya_yuklemeleri', ['islem_kodu'], unique=False)
    op.create_index('idx_dosya_silme_tarihi', 'dosya_yuklemeleri', ['silme_tarihi'], unique=False)
    op.create_index('idx_dosya_yukleme_tarihi', 'dosya_yuklemeleri', ['yukleme_tarihi'], unique=False)
    op.create_index(op.f('ix_dosya_yuklemeleri_islem_kodu'), 'dosya_yuklemeleri', ['islem_kodu'], unique=True)
    op.create_foreign_key(None, 'dosya_yuklemeleri', 'kullanicilar', ['yuklenen_kullanici_id'], ['id'])
    op.alter_column('hata_loglari', 'olusturma_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('kullanici_id'), table_name='hata_loglari')
    op.create_foreign_key(None, 'hata_loglari', 'kullanicilar', ['kullanici_id'], ['id'])
    op.alter_column('katlar', 'olusturma_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('otel_id'), table_name='katlar')
    op.create_foreign_key(None, 'katlar', 'oteller', ['otel_id'], ['id'])
    op.create_index('idx_kullanici_otel', 'kullanici_otel', ['kullanici_id', 'otel_id'], unique=False)
    op.create_unique_constraint('uq_kullanici_otel', 'kullanici_otel', ['kullanici_id', 'otel_id'])
    op.create_foreign_key(None, 'kullanici_otel', 'kullanicilar', ['kullanici_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'kullanici_otel', 'oteller', ['otel_id'], ['id'], ondelete='CASCADE')
    op.alter_column('kullanicilar', 'rol',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('sistem_yoneticisi', 'admin', 'depo_sorumlusu', 'kat_sorumlusu', name='kullanici_rol'),
               existing_nullable=False,
               postgresql_using='rol::kullanici_rol')
    op.alter_column('kullanicilar', 'olusturma_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('kullanicilar', 'son_giris',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('kullanici_adi'), table_name='kullanicilar')
    op.create_unique_constraint(None, 'kullanicilar', ['kullanici_adi'])
    op.alter_column('minibar_dolum_talepleri', 'talep_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('minibar_dolum_talepleri', 'durum',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('beklemede', 'onaylandi', 'reddedildi', 'tamamlandi', 'iptal', name='dolum_talep_durum'),
               existing_nullable=False,
               postgresql_using='durum::dolum_talep_durum')
    op.alter_column('minibar_dolum_talepleri', 'tamamlanma_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_oda_durum'), table_name='minibar_dolum_talepleri')
    op.create_index('idx_oda_durum', 'minibar_dolum_talepleri', ['oda_id', 'durum'], unique=False)
    op.create_foreign_key(None, 'minibar_dolum_talepleri', 'odalar', ['oda_id'], ['id'])
    op.drop_index(op.f('islem_id'), table_name='minibar_islem_detay')
    op.drop_index(op.f('urun_id'), table_name='minibar_islem_detay')
    op.drop_index(op.f('zimmet_detay_id'), table_name='minibar_islem_detay')
    op.create_foreign_key(None, 'minibar_islem_detay', 'minibar_islemleri', ['islem_id'], ['id'])
    op.create_foreign_key(None, 'minibar_islem_detay', 'urunler', ['urun_id'], ['id'])
    op.create_foreign_key(None, 'minibar_islem_detay', 'personel_zimmet_detay', ['zimmet_detay_id'], ['id'])
    op.alter_column('minibar_islemleri', 'islem_tipi',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ilk_dolum', 'yeniden_dolum', 'eksik_tamamlama', 'sayim', 'duzeltme', 'kontrol', 'doldurma', 'ek_dolum', name='minibar_islem_tipi'),
               existing_nullable=False,
               postgresql_using='islem_tipi::minibar_islem_tipi')
    op.alter_column('minibar_islemleri', 'islem_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_oda_tarih'), table_name='minibar_islemleri')
    op.create_index('idx_oda_tarih', 'minibar_islemleri', ['oda_id', 'islem_tarihi'], unique=False)
    op.drop_index(op.f('idx_personel_tarih'), table_name='minibar_islemleri')
    op.create_index('idx_personel_tarih', 'minibar_islemleri', ['personel_id', 'islem_tarihi'], unique=False)
    op.create_foreign_key(None, 'minibar_islemleri', 'kullanicilar', ['personel_id'], ['id'])
    op.create_foreign_key(None, 'minibar_islemleri', 'odalar', ['oda_id'], ['id'])
    op.create_index('idx_misafir_cikis', 'misafir_kayitlari', ['cikis_tarihi'], unique=False)
    op.create_index('idx_misafir_giris', 'misafir_kayitlari', ['giris_tarihi'], unique=False)
    op.create_index('idx_misafir_islem_kodu', 'misafir_kayitlari', ['islem_kodu'], unique=False)
    op.create_index('idx_misafir_oda_tarih', 'misafir_kayitlari', ['oda_id', 'giris_tarihi', 'cikis_tarihi'], unique=False)
    op.create_index(op.f('ix_misafir_kayitlari_cikis_tarihi'), 'misafir_kayitlari', ['cikis_tarihi'], unique=False)
    op.create_index(op.f('ix_misafir_kayitlari_giris_tarihi'), 'misafir_kayitlari', ['giris_tarihi'], unique=False)
    op.create_index(op.f('ix_misafir_kayitlari_islem_kodu'), 'misafir_kayitlari', ['islem_kodu'], unique=False)
    op.create_foreign_key(None, 'misafir_kayitlari', 'kullanicilar', ['olusturan_id'], ['id'])
    op.create_foreign_key(None, 'misafir_kayitlari', 'odalar', ['oda_id'], ['id'])
    op.alter_column('ml_alerts', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index('idx_ml_alerts_created', 'ml_alerts', ['created_at'], unique=False)
    op.create_index('idx_ml_alerts_entity', 'ml_alerts', ['entity_id'], unique=False)
    op.create_index('idx_ml_alerts_severity_read', 'ml_alerts', ['severity', 'is_read'], unique=False)
    op.create_foreign_key(None, 'ml_alerts', 'kullanicilar', ['resolved_by_id'], ['id'])
    op.alter_column('ml_features', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ml_features', 'feature_version',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ml_features', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_ml_features_entity_time'), table_name='ml_features')
    op.create_index('idx_ml_features_entity_time', 'ml_features', ['entity_id', 'timestamp'], unique=False)
    op.drop_index(op.f('idx_ml_features_timestamp'), table_name='ml_features')
    op.create_index('idx_ml_features_timestamp', 'ml_features', ['timestamp'], unique=False)
    op.create_index('idx_ml_metrics_entity', 'ml_metrics', ['entity_id'], unique=False)
    op.create_index('idx_ml_metrics_type_time', 'ml_metrics', ['metric_type', 'timestamp'], unique=False)
    op.alter_column('ml_models', 'model_path',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_ml_models_path'), table_name='ml_models')
    op.create_index('idx_ml_training_logs_date', 'ml_training_logs', ['training_start'], unique=False)
    op.create_foreign_key(None, 'ml_training_logs', 'ml_models', ['model_id'], ['id'])
    op.alter_column('odalar', 'oda_tipi',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('odalar', 'olusturma_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('odalar', 'qr_kod_olusturma_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('kat_id'), table_name='odalar')
    op.drop_index(op.f('oda_no'), table_name='odalar')
    op.drop_index(op.f('qr_kod_token'), table_name='odalar')
    op.create_unique_constraint(None, 'odalar', ['qr_kod_token'])
    op.create_unique_constraint(None, 'odalar', ['oda_no'])
    op.create_foreign_key(None, 'odalar', 'katlar', ['kat_id'], ['id'])
    op.alter_column('oteller', 'olusturma_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('otomatik_raporlar', 'rapor_tipi',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('gunluk', 'haftalik', 'aylik', name='rapor_tipi'),
               existing_nullable=False,
               postgresql_using='rapor_tipi::rapor_tipi')
    op.alter_column('otomatik_raporlar', 'rapor_verisi',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('otomatik_raporlar', 'olusturma_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('idx_rapor_tipi_tarih'), table_name='otomatik_raporlar')
    op.create_index('idx_rapor_tipi_tarih', 'otomatik_raporlar', ['rapor_tipi', 'olusturma_tarihi'], unique=False)
    op.alter_column('personel_zimmet', 'zimmet_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('personel_zimmet', 'durum',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('aktif', 'iade_edildi', 'iptal', name='zimmet_durum'),
               existing_nullable=True,
               postgresql_using='durum::zimmet_durum')
    op.drop_index(op.f('personel_id'), table_name='personel_zimmet')
    op.drop_index(op.f('teslim_eden_id'), table_name='personel_zimmet')
    op.create_foreign_key(None, 'personel_zimmet', 'kullanicilar', ['teslim_eden_id'], ['id'])
    op.create_foreign_key(None, 'personel_zimmet', 'kullanicilar', ['personel_id'], ['id'])
    op.drop_index(op.f('zimmet_id'), table_name='personel_zimmet_detay')
    op.create_foreign_key(None, 'personel_zimmet_detay', 'urunler', ['urun_id'], ['id'])
    op.create_foreign_key(None, 'personel_zimmet_detay', 'personel_zimmet', ['zimmet_id'], ['id'])
    op.alter_column('qr_kod_okutma_loglari', 'okutma_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('qr_kod_okutma_loglari', 'okutma_tipi',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('misafir_okutma', 'personel_kontrol', 'sistem_kontrol', name='qr_okutma_tipi'),
               existing_nullable=False,
               postgresql_using='okutma_tipi::qr_okutma_tipi')
    op.create_index('idx_kullanici_tarih', 'qr_kod_okutma_loglari', ['kullanici_id', 'okutma_tarihi'], unique=False)
    op.create_index('idx_oda_tarih', 'qr_kod_okutma_loglari', ['oda_id', 'okutma_tarihi'], unique=False)
    op.create_foreign_key(None, 'qr_kod_okutma_loglari', 'kullanicilar', ['kullanici_id'], ['id'])
    op.create_foreign_key(None, 'qr_kod_okutma_loglari', 'odalar', ['oda_id'], ['id'])
    op.drop_index(op.f('anahtar'), table_name='sistem_ayarlari')
    op.create_unique_constraint(None, 'sistem_ayarlari', ['anahtar'])
    op.alter_column('sistem_loglari', 'islem_detay',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('sistem_loglari', 'islem_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'sistem_loglari', 'kullanicilar', ['kullanici_id'], ['id'])
    op.alter_column('stok_hareketleri', 'hareket_tipi',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('giris', 'cikis', 'transfer', 'devir', 'sayim', 'fire', name='hareket_tipi'),
               existing_nullable=False,
               postgresql_using='hareket_tipi::hareket_tipi')
    op.alter_column('stok_hareketleri', 'islem_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('islem_yapan_id'), table_name='stok_hareketleri')
    op.create_foreign_key(None, 'stok_hareketleri', 'urunler', ['urun_id'], ['id'])
    op.create_foreign_key(None, 'stok_hareketleri', 'kullanicilar', ['islem_yapan_id'], ['id'])
    op.alter_column('urun_gruplari', 'olusturma_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('grup_adi'), table_name='urun_gruplari')
    op.create_unique_constraint(None, 'urun_gruplari', ['grup_adi'])
    op.alter_column('urunler', 'olusturma_tarihi',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('barkod'), table_name='urunler')
    op.drop_index(op.f('grup_id'), table_name='urunler')
    op.create_unique_constraint(None, 'urunler', ['barkod'])
    op.create_foreign_key(None, 'urunler', 'urun_gruplari', ['grup_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urunler', type_='foreignkey')
    op.drop_constraint(None, 'urunler', type_='unique')
    op.create_index(op.f('grup_id'), 'urunler', ['grup_id'], unique=False)
    op.create_index(op.f('barkod'), 'urunler', ['barkod'], unique=True)
    op.alter_column('urunler', 'olusturma_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_constraint(None, 'urun_gruplari', type_='unique')
    op.create_index(op.f('grup_adi'), 'urun_gruplari', ['grup_adi'], unique=True)
    op.alter_column('urun_gruplari', 'olusturma_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_constraint(None, 'stok_hareketleri', type_='foreignkey')
    op.drop_constraint(None, 'stok_hareketleri', type_='foreignkey')
    op.create_index(op.f('islem_yapan_id'), 'stok_hareketleri', ['islem_yapan_id'], unique=False)
    op.alter_column('stok_hareketleri', 'islem_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('stok_hareketleri', 'hareket_tipi',
               existing_type=sa.Enum('giris', 'cikis', 'transfer', 'devir', 'sayim', 'fire', name='hareket_tipi'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'sistem_loglari', type_='foreignkey')
    op.alter_column('sistem_loglari', 'islem_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('sistem_loglari', 'islem_detay',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'sistem_ayarlari', type_='unique')
    op.create_index(op.f('anahtar'), 'sistem_ayarlari', ['anahtar'], unique=True)
    op.drop_constraint(None, 'qr_kod_okutma_loglari', type_='foreignkey')
    op.drop_constraint(None, 'qr_kod_okutma_loglari', type_='foreignkey')
    op.drop_index('idx_oda_tarih', table_name='qr_kod_okutma_loglari')
    op.drop_index('idx_kullanici_tarih', table_name='qr_kod_okutma_loglari')
    op.alter_column('qr_kod_okutma_loglari', 'okutma_tipi',
               existing_type=sa.Enum('misafir_okutma', 'personel_kontrol', 'sistem_kontrol', name='qr_okutma_tipi'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('qr_kod_okutma_loglari', 'okutma_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint(None, 'personel_zimmet_detay', type_='foreignkey')
    op.drop_constraint(None, 'personel_zimmet_detay', type_='foreignkey')
    op.create_index(op.f('zimmet_id'), 'personel_zimmet_detay', ['zimmet_id'], unique=False)
    op.drop_constraint(None, 'personel_zimmet', type_='foreignkey')
    op.drop_constraint(None, 'personel_zimmet', type_='foreignkey')
    op.create_index(op.f('teslim_eden_id'), 'personel_zimmet', ['teslim_eden_id'], unique=False)
    op.create_index(op.f('personel_id'), 'personel_zimmet', ['personel_id'], unique=False)
    op.alter_column('personel_zimmet', 'durum',
               existing_type=sa.Enum('aktif', 'iade_edildi', 'iptal', name='zimmet_durum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('personel_zimmet', 'zimmet_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_index('idx_rapor_tipi_tarih', table_name='otomatik_raporlar')
    op.create_index(op.f('idx_rapor_tipi_tarih'), 'otomatik_raporlar', ['rapor_tipi'], unique=False)
    op.alter_column('otomatik_raporlar', 'olusturma_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('otomatik_raporlar', 'rapor_verisi',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('otomatik_raporlar', 'rapor_tipi',
               existing_type=sa.Enum('gunluk', 'haftalik', 'aylik', name='rapor_tipi'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('oteller', 'olusturma_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_constraint(None, 'odalar', type_='foreignkey')
    op.drop_constraint(None, 'odalar', type_='unique')
    op.drop_constraint(None, 'odalar', type_='unique')
    op.create_index(op.f('qr_kod_token'), 'odalar', ['qr_kod_token'], unique=True)
    op.create_index(op.f('oda_no'), 'odalar', ['oda_no'], unique=True)
    op.create_index(op.f('kat_id'), 'odalar', ['kat_id'], unique=False)
    op.alter_column('odalar', 'qr_kod_olusturma_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('odalar', 'olusturma_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('odalar', 'oda_tipi',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'ml_training_logs', type_='foreignkey')
    op.drop_index('idx_ml_training_logs_date', table_name='ml_training_logs')
    op.create_index(op.f('idx_ml_models_path'), 'ml_models', ['model_path'], unique=False)
    op.alter_column('ml_models', 'model_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_index('idx_ml_metrics_type_time', table_name='ml_metrics')
    op.drop_index('idx_ml_metrics_entity', table_name='ml_metrics')
    op.drop_index('idx_ml_features_timestamp', table_name='ml_features')
    op.create_index(op.f('idx_ml_features_timestamp'), 'ml_features', [sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index('idx_ml_features_entity_time', table_name='ml_features')
    op.create_index(op.f('idx_ml_features_entity_time'), 'ml_features', ['entity_id', sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('ml_features', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('ml_features', 'feature_version',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'1.0'::character varying"),
               existing_nullable=True)
    op.alter_column('ml_features', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_constraint(None, 'ml_alerts', type_='foreignkey')
    op.drop_index('idx_ml_alerts_severity_read', table_name='ml_alerts')
    op.drop_index('idx_ml_alerts_entity', table_name='ml_alerts')
    op.drop_index('idx_ml_alerts_created', table_name='ml_alerts')
    op.alter_column('ml_alerts', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'misafir_kayitlari', type_='foreignkey')
    op.drop_constraint(None, 'misafir_kayitlari', type_='foreignkey')
    op.drop_index(op.f('ix_misafir_kayitlari_islem_kodu'), table_name='misafir_kayitlari')
    op.drop_index(op.f('ix_misafir_kayitlari_giris_tarihi'), table_name='misafir_kayitlari')
    op.drop_index(op.f('ix_misafir_kayitlari_cikis_tarihi'), table_name='misafir_kayitlari')
    op.drop_index('idx_misafir_oda_tarih', table_name='misafir_kayitlari')
    op.drop_index('idx_misafir_islem_kodu', table_name='misafir_kayitlari')
    op.drop_index('idx_misafir_giris', table_name='misafir_kayitlari')
    op.drop_index('idx_misafir_cikis', table_name='misafir_kayitlari')
    op.drop_constraint(None, 'minibar_islemleri', type_='foreignkey')
    op.drop_constraint(None, 'minibar_islemleri', type_='foreignkey')
    op.drop_index('idx_personel_tarih', table_name='minibar_islemleri')
    op.create_index(op.f('idx_personel_tarih'), 'minibar_islemleri', ['personel_id'], unique=False)
    op.drop_index('idx_oda_tarih', table_name='minibar_islemleri')
    op.create_index(op.f('idx_oda_tarih'), 'minibar_islemleri', ['oda_id'], unique=False)
    op.alter_column('minibar_islemleri', 'islem_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('minibar_islemleri', 'islem_tipi',
               existing_type=sa.Enum('ilk_dolum', 'yeniden_dolum', 'eksik_tamamlama', 'sayim', 'duzeltme', 'kontrol', 'doldurma', 'ek_dolum', name='minibar_islem_tipi'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'minibar_islem_detay', type_='foreignkey')
    op.drop_constraint(None, 'minibar_islem_detay', type_='foreignkey')
    op.drop_constraint(None, 'minibar_islem_detay', type_='foreignkey')
    op.create_index(op.f('zimmet_detay_id'), 'minibar_islem_detay', ['zimmet_detay_id'], unique=False)
    op.create_index(op.f('urun_id'), 'minibar_islem_detay', ['urun_id'], unique=False)
    op.create_index(op.f('islem_id'), 'minibar_islem_detay', ['islem_id'], unique=False)
    op.drop_constraint(None, 'minibar_dolum_talepleri', type_='foreignkey')
    op.drop_index('idx_oda_durum', table_name='minibar_dolum_talepleri')
    op.create_index(op.f('idx_oda_durum'), 'minibar_dolum_talepleri', ['oda_id'], unique=False)
    op.alter_column('minibar_dolum_talepleri', 'tamamlanma_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('minibar_dolum_talepleri', 'durum',
               existing_type=sa.Enum('beklemede', 'onaylandi', 'reddedildi', 'tamamlandi', 'iptal', name='dolum_talep_durum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('minibar_dolum_talepleri', 'talep_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint(None, 'kullanicilar', type_='unique')
    op.create_index(op.f('kullanici_adi'), 'kullanicilar', ['kullanici_adi'], unique=True)
    op.alter_column('kullanicilar', 'son_giris',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('kullanicilar', 'olusturma_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('kullanicilar', 'rol',
               existing_type=sa.Enum('sistem_yoneticisi', 'admin', 'depo_sorumlusu', 'kat_sorumlusu', name='kullanici_rol'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'kullanici_otel', type_='foreignkey')
    op.drop_constraint(None, 'kullanici_otel', type_='foreignkey')
    op.drop_constraint('uq_kullanici_otel', 'kullanici_otel', type_='unique')
    op.drop_index('idx_kullanici_otel', table_name='kullanici_otel')
    op.drop_constraint(None, 'katlar', type_='foreignkey')
    op.create_index(op.f('otel_id'), 'katlar', ['otel_id'], unique=False)
    op.alter_column('katlar', 'olusturma_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_constraint(None, 'hata_loglari', type_='foreignkey')
    op.create_index(op.f('kullanici_id'), 'hata_loglari', ['kullanici_id'], unique=False)
    op.alter_column('hata_loglari', 'olusturma_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint(None, 'dosya_yuklemeleri', type_='foreignkey')
    op.drop_index(op.f('ix_dosya_yuklemeleri_islem_kodu'), table_name='dosya_yuklemeleri')
    op.drop_index('idx_dosya_yukleme_tarihi', table_name='dosya_yuklemeleri')
    op.drop_index('idx_dosya_silme_tarihi', table_name='dosya_yuklemeleri')
    op.drop_index('idx_dosya_islem_kodu', table_name='dosya_yuklemeleri')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index('idx_tablo_kayit', table_name='audit_logs')
    op.create_index(op.f('idx_tablo_kayit'), 'audit_logs', ['tablo_adi'], unique=False)
    op.drop_index('idx_kullanici_tarih', table_name='audit_logs')
    op.create_index(op.f('idx_kullanici_tarih'), 'audit_logs', ['kullanici_id'], unique=False)
    op.alter_column('audit_logs', 'islem_tarihi',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'yeni_deger',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'eski_deger',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'islem_tipi',
               existing_type=sa.Enum('login', 'logout', 'create', 'update', 'delete', 'view', 'export', 'import', 'backup', 'restore', name='audit_islem_tipi'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('fiyat_guncelleme_kurallari',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('urun_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kural_tipi', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('artirma_orani', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('azaltma_orani', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('min_fiyat', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_fiyat', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('aktif', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('son_uygulama', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('olusturma_tarihi', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("kural_tipi::text = ANY (ARRAY['otomatik_artir'::character varying::text, 'otomatik_azalt'::character varying::text, 'rakip_fiyat'::character varying::text])", name=op.f('fiyat_guncelleme_kurallari_kural_tipi_check')),
    sa.CheckConstraint('min_fiyat IS NULL OR max_fiyat IS NULL OR min_fiyat <= max_fiyat', name=op.f('chk_min_max_fiyat'))
    )
    op.create_table('donemsel_kar_analizi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('otel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('donem_tipi', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('baslangic_tarihi', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('bitis_tarihi', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('toplam_gelir', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('toplam_maliyet', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('net_kar', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('kar_marji', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('analiz_verisi', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('olusturma_tarihi', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("donem_tipi::text = ANY (ARRAY['gunluk'::character varying::text, 'haftalik'::character varying::text, 'aylik'::character varying::text])", name=op.f('donemsel_kar_analizi_donem_tipi_check')),
    sa.CheckConstraint('bitis_tarihi >= baslangic_tarihi', name=op.f('chk_donem_tarih')),
    sa.CheckConstraint('kar_marji >= 0::double precision AND kar_marji <= 100::double precision', name=op.f('chk_kar_marji'))
    )
    op.create_table('bedelsiz_kullanim_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('oda_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('urun_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('miktar', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('islem_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kullanilma_tarihi', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('limit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('miktar > 0', name=op.f('chk_miktar'))
    )
    op.create_table('urun_tedarikci_fiyatlari',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('urun_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tedarikci_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alis_fiyati', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('minimum_miktar', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('baslangic_tarihi', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('bitis_tarihi', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('aktif', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('olusturma_tarihi', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('olusturan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('alis_fiyati >= 0::numeric', name=op.f('chk_alis_fiyati')),
    sa.CheckConstraint('minimum_miktar > 0', name=op.f('chk_minimum_miktar'))
    )
    op.create_table('tedarikciler',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tedarikci_adi', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('iletisim_bilgileri', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('aktif', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('olusturma_tarihi', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('guncelleme_tarihi', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True)
    )
    op.create_table('oda_tipi_satis_fiyatlari',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('oda_tipi', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('urun_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('satis_fiyati', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('baslangic_tarihi', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('bitis_tarihi', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('aktif', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.CheckConstraint('satis_fiyati >= 0::numeric', name=op.f('chk_satis_fiyati'))
    )
    op.create_table('tuketim_kalibi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('urun_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('oda_tipi', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('gunler_haftasi', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('saat_araligi', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ortalama_tuketim', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mevsimsel_degisim', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('olusturma_tarihi', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('ortalama_tuketim > 0::double precision', name=op.f('chk_ortalama_tuketim'))
    )
    op.create_table('sezon_fiyatlandirma',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sezon_adi', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('baslangic_tarihi', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('bitis_tarihi', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('urun_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fiyat_carpani', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=False),
    sa.Column('aktif', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.CheckConstraint('bitis_tarihi > baslangic_tarihi', name=op.f('chk_tarih_araligi')),
    sa.CheckConstraint('fiyat_carpani > 0::double precision', name=op.f('chk_fiyat_carpani'))
    )
    op.create_table('kampanyalar',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('kampanya_adi', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('baslangic_tarihi', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('bitis_tarihi', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('urun_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indirim_tipi', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('indirim_degeri', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('min_siparis_miktari', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('max_kullanim_sayisi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kullanilan_sayisi', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('aktif', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.CheckConstraint("indirim_tipi::text = 'yuzde'::text AND indirim_degeri >= 0::numeric AND indirim_degeri <= 100::numeric OR indirim_tipi::text = 'tutar'::text AND indirim_degeri >= 0::numeric", name=op.f('chk_indirim_yuzde')),
    sa.CheckConstraint("indirim_tipi::text = ANY (ARRAY['yuzde'::character varying::text, 'tutar'::character varying::text])", name=op.f('kampanyalar_indirim_tipi_check')),
    sa.CheckConstraint('bitis_tarihi > baslangic_tarihi', name=op.f('chk_kampanya_tarih')),
    sa.CheckConstraint('min_siparis_miktari > 0', name=op.f('chk_min_siparis'))
    )
    op.create_table('bedelsiz_limitler',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('oda_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('urun_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_miktar', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kullanilan_miktar', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('baslangic_tarihi', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('bitis_tarihi', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('limit_tipi', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('kampanya_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("limit_tipi::text = ANY (ARRAY['misafir'::character varying::text, 'kampanya'::character varying::text, 'personel'::character varying::text])", name=op.f('bedelsiz_limitler_limit_tipi_check')),
    sa.CheckConstraint('kullanilan_miktar <= max_miktar', name=op.f('chk_kullanilan_max')),
    sa.CheckConstraint('kullanilan_miktar >= 0', name=op.f('chk_kullanilan_miktar')),
    sa.CheckConstraint('max_miktar > 0', name=op.f('chk_max_miktar'))
    )
    op.create_table('roi_hesaplamalari',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('otel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('urun_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kategori_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hesaplama_tipi', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('baslangic_tarihi', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('bitis_tarihi', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('toplam_yatirim', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('toplam_getiri', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_getiri', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('roi_orani', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hesaplama_detaylari', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('olusturma_tarihi', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("roi_orani >= '-100'::integer::double precision", name=op.f('chk_roi_orani')),
    sa.CheckConstraint('bitis_tarihi >= baslangic_tarihi', name=op.f('chk_roi_tarih'))
    )
    op.create_table('urun_fiyat_gecmisi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('urun_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('eski_fiyat', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('yeni_fiyat', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('degisiklik_tipi', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('degisiklik_tarihi', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('degisiklik_sebebi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('olusturan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("degisiklik_tipi::text = ANY (ARRAY['alis_fiyati'::character varying::text, 'satis_fiyati'::character varying::text, 'kampanya'::character varying::text])", name=op.f('urun_fiyat_gecmisi_degisiklik_tipi_check'))
    )
    op.create_table('urun_trend_analizi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('urun_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('donem', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('baslangic_tarihi', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('tuketim_miktari', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tuketim_degeri', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('onceki_donem_miktari', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('degisim_orani', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trend_yonu', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.CheckConstraint("degisim_orani >= '-100'::integer::double precision AND degisim_orani <= 100::double precision", name=op.f('chk_degisim_orani')),
    sa.CheckConstraint("donem::text = ANY (ARRAY['haftalik'::character varying::text, 'aylik'::character varying::text, 'yillik'::character varying::text])", name=op.f('urun_trend_analizi_donem_check')),
    sa.CheckConstraint("trend_yonu::text = ANY (ARRAY['yukselen'::character varying::text, 'dusen'::character varying::text, 'sabit'::character varying::text])", name=op.f('urun_trend_analizi_trend_yonu_check')),
    sa.CheckConstraint('tuketim_miktari >= 0', name=op.f('chk_tuketim_miktari'))
    )
    op.drop_index('idx_query_logs_timestamp', table_name='query_logs')
    op.drop_index('idx_query_logs_time', table_name='query_logs')
    op.drop_index('idx_query_logs_endpoint', table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index('idx_config_audit_filename', table_name='config_audit')
    op.drop_index('idx_config_audit_changed', table_name='config_audit')
    op.drop_table('config_audit')
    op.drop_index('idx_backup_history_created', table_name='backup_history')
    op.drop_index('idx_backup_history_backup_id', table_name='backup_history')
    op.drop_table('backup_history')
    op.drop_index('idx_background_jobs_status', table_name='background_jobs')
    op.drop_index('idx_background_jobs_started', table_name='background_jobs')
    op.drop_index('idx_background_jobs_job_id', table_name='background_jobs')
    op.drop_table('background_jobs')
    # ### end Alembic commands ###
